name: diabetes_frontend
description: Diabetes management app (Flutter Web)
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  fl_chart: ^0.66.0
  google_maps_flutter: ^2.12.2
  flutter_local_notifications: ^18.0.0
  timezone: ^0.10.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_native_splash: ^2.4.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  

flutter:
  uses-material-design: true
  assets:
    - assets/countries.json
    - assets/cities.json
    - assets/diabetes_meds.json
    - assets/diabetes_meals.json
    - assets/physical_activities.json
    - assets/diabetes_logo.png
    - assets/diabetes_illustration.png
    - assets/icon.png
    - assets/icon_no_back.png
    - packages/timezone/data/latest_all.tzf
    - assets/sukari.png

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#B8A5F2" # Added root-level color for the splash screen background
  image: assets/icon_no_back.png # Optional: The logo/image to display on the splash screen
  android_12:
    icon_background_color: "#B8A5F2" # Background color for the icon in Android 12+
    image: assets/icon_no_back.png # Icon for Android 12+ splash screen
    branding: assets/sukari.png # Branding image for Android 12+